### PR TITLE
RK-9874 - Gilad/save deployments in as state

### PR DESCRIPTION
**Pull request by Gilwe**
Fixing the following issues:

1. Saving a state of the running deployments in the operator so on `helm upgrade` we will run the patching mechanism on all deployments in the cluster
2. Remove java SDK from deployments which were patched and then didn't match the new config
3. appended to JAVA_TOOL_OPTIONS env var if it is already populated

### CODE REVIEW

**Comment by ElDuderinos** [comment]
@Gilwe help me out here with a description? 😁

**Comment by Gilwe** [comment]
@ElDuderinos bahh my bad
added that

**Comment by ElDuderinos** [comment]
@Gilwe What were the steps you've done to test the JAVA_TOOL_OPTIONS appending?

**Comment by Gilwe** [comment]
simple, had 2 deployments: one with no `JAVA_TOOL_OPTIONS` and the other with that env var (value: `"-Xmx512m -Xms64m"`).
Made sure that the operator appends the `-javaagent:/rookout/rook.jar` with a single space and to the one with the env var and that the rook starts.

Tested also the other way: on removing the deployment from the matcher I checked that the env var is back to its previous value.

**Review by ElDuderinos — APPROVED** [review]

**Pull request merged**
