### PR TITLE
RK-11664 - Update README.md

### PR DESCRIPTION
**Pull request by ElinorSwery**

### CODE REVIEW

**Comment by lirook** [comment]
@ElinorSwery (it's either /jira open task or /jira open bug. maybe it also works with story)

@ElDuderinos perhaps we want to make this repo private?

**Comment by lirook** [comment]
@ElinorSwery (it's either jira open task or jira open bug. maybe it also works with story)

@ElDuderinos perhaps we want to make this repo private?

**Review by adirook — APPROVED** [review]

**Comment by lirook** [comment]
Based on @ElinorSwery's comment saying we shouldn't see this repo in the RH operator page, I am closing this PR, and we can go ahead and make this repository private.

**Pull request closed without merging**
